volumes:
  ny_taxi_postgres_data:
    driver: local
  pgadmin_data:
  kestra_postgres_data:
    driver: local
  kestra_data:
    driver: local

services:
  pgdatabase:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi"
    volumes:
      # ✅ Postgres 18+ expects mount here
      - ny_taxi_postgres_data:/var/lib/postgresql
    ports:
      - "5434:5432"
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"
    networks:
      - pgnetwork

  kestra_postgres:
    image: postgres:18
    restart: always
    volumes:
      # ✅ Postgres 18+ expects mount here
      - kestra_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - pgnetwork

  kestra:
    image: kestra/kestra:v1.1
    pull_policy: always
    user: "root"
    command: server standalone
    #env_file:
    #  - .env
    volumes:
      - kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ./secrets:/secrets:ro #to get the GCP secret in json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp-sa.json  #to get the GCP secret in json 
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4

        kestra:
          server:
            basicAuth:
              username: "admin@kestra.io" 
              password: Admin1234
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    ports:
      - "8084:8080"
      - "8083:8081"
    depends_on:
      kestra_postgres:
        condition: service_healthy
    networks:
      - pgnetwork

networks:
  pgnetwork:
